columns:
    - [PRODUCT_ID, observation_id, text]
    - [LINE_SAMPLES, samples, integer]
    - [IMAGE_LINES, lines, integer]
    - [CENTER_LATITUDE, center_latitude, real]
    - [CENTER_LONGITUDE, center_longitude, real]
    - [NORTH_AZIMUTH, north_azimuth, real]
    - [SCALED_PIXEL_WIDTH, pixel_width, real]
    - [VOLUME_ID, volume_id, text]
    - [FILE_NAME_SPECIFICATION, file_name_specification, text]
    - [PRODUCT_VERSION_ID, product_version_id, text]
    - [TARGET_NAME, target_name, text]
    - [ORBIT_NUMBER, orbit_number, integer]
    - [MISSION_PHASE_NAME, mission_phase_name, text]
    - [RATIONALE_DESC, description, text]
    - [START_TIME, start_time, timestamp]
    - [STOP_TIME, stop_time, timestamp]
    - [SPACECRAFT_CLOCK_START_COUNT, sclk_start, real]
    - [SPACECRAFT_CLOCK_STOP_COUNT, sclk_stop, real]
    - [FILTER_NAME, filter_name, text]
    - [EMISSION_ANGLE, emission_angle, real]
    - [INCIDENCE_ANGLE, incidence_angle, real]
    - [PHASE_ANGLE, phase_angle, real]
    - [SPACECRAFT_ALTITUDE, spacecraft_altitude, real]
    - [TARGET_CENTER_DISTANCE, target_center_distance, real]
    - [SUB_SOLAR_AZIMUTH, sub_solar_azimuth, real]
    - [SUB_SOLAR_LATITUDE, sub_solar_latitude, real]
    - [SUB_SOLAR_LONGITUDE, sub_solar_longitude, real]
    - [SUB_SPACECRAFT_LATITUDE, sub_spacecraft_latitude, real]
    - [SUB_SPACECRAFT_LONGITUDE, sub_spacecraft_longitude, real]
    - [SOLAR_DISTANCE, solar_distance, real]
    - [SOLAR_LONGITUDE, solar_longitude, real]

scale_factors:
    SPACECRAFT_ALTITUDE: 1000 # km to m
    SOLAR_DISTANCE: 1000 # km to m

index:
    - observation_id

segmentation:
    resolution: 50000
